package com.digitalascetic.app.domain.service

import javax.inject.Inject

class GeminiReflectionEngine @Inject constructor() : ReflectionEngine {
    override suspend fun generateDailyPrompt(contextJson: String): String {
        return "Stub: Prompt generated by Gemini Nano for context: $contextJson"
    }

    override suspend fun summarizeJournalEntries(entryIds: List<String>): String {
        return "Stub: Summary of entries $entryIds"
    }
}
